---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-flyway
images:
- name: docker.io/rmiguel/flyway
  newTag: "3"

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: nginx-deployment

secretGenerator:
- name: nginx-deployment-env
  options:
    labels:
      app: nginx-deployment
  envs:
  - nginx-deployment-secret.env

configMapGenerator:
- name: nginx-deployment-env
  envs:
  - nginx-deployment-configmap.env
...
